### ISSUE TITLE
how to use it 

### ISSUE THREAD

**Issue by jpfree** [flinhong/imageuploader#1]
i install ipfs ,run ipfd deamon,and  run it in http web,but i don't know where upload the image

**Comment by flinhong** [comment]
Sorry about this. This repo is not finished yet.

To upload a image, you can go through ipfs’s official demo: https://ipfs.io/docs/getting-started/

Best wishes,
Frank Lin

On 3 Jan 2018, at 12:52 PM, jpfree <notifications@github.com<mailto:notifications@github.com>> wrote:


i install ipfs ,run ipfd deamon,and run it in http web,but i don't know where upload the image

**Comment by jpfree** [comment]
谢谢，很好的作品
